name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "environment"
  environment:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          channel-priority: strict  
          activate-environment: env_seqitope
          environment-file: environment_explicit.yaml
          auto-activate-base: false
          use-only-tar-bz2: true
      - name: Set R cache folder
        run: |
          mkdir ~/r_pkgs_dir
      - name: Cache R
        uses: actions/cache@v2
        env:
          R_LIBS_USER: ~/r_pkgs_dir
        with:
          path: ${{ env.R_LIBS_USER }} 
          key: ${{ runner.os }}-r-${{ hashFiles('environment_explicit.yaml') }}           
      # SYNCSA not included in conda yet, remove when we fix this
      - name: Install R dependencies
        env:
          R_LIBS_USER: ~/r_pkgs_dir
        run: | #conda activate env_seqitope
          echo $R_LIBS_USER
          which Rscript
          Rscript -e 'if (!require("SYNCSA")) install.packages("SYNCSA", lib=Sys.getenv("R_LIBS_USER"), repos = "http://cran.us.r-project.org")'
      - name: Test R installation
        env:
          R_LIBS_USER: ~/r_pkgs_dir
        run: | #export R_LIBS_USER="~/r_pkgs_dir"
          Rscript -e 'library("deepSNV"); library("SYNCSA")'
      - name: Test output
        run: |
          cat test1.txt test2.txt > test_output.txt
          diff test_output.txt test3.txt || exit 1
          
          
        
          

